### ISSUE TITLE
0.2.2 not published to npm

### ISSUE THREAD

**Issue by amir-arad** [tweakpane/plugin-camerakit#5]
I was going to open an issue for missing type definitions, but I see that #4 was opened and closed.
However, latest version in npmjs.com is 0.2.1 , so I can't enjoy the fix :(

tweakpane is awesome, by the way :) , I'm in the process of replacing old dat.gui with it and I'm eager to try out all these plugins

**Comment by cocopon** [comment]
Ah sorry, just published 0.2.2.

**Comment by amir-arad** [comment]
thanks!
